// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// SubscriptionMetis is the predicate function for subscriptionmetis builders.
type SubscriptionMetis func(*sql.Selector)

// SubscriptionMoonbeam is the predicate function for subscriptionmoonbeam builders.
type SubscriptionMoonbeam func(*sql.Selector)

// SubscriptionZkEVM is the predicate function for subscriptionzkevm builders.
type SubscriptionZkEVM func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
