// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arjunmal1311/fans_flow_on_chain/backend/ent/predicate"
	"arjunmal1311/fans_flow_on_chain/backend/ent/subscriptionmoonbeam"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscriptionMoonbeamUpdate is the builder for updating SubscriptionMoonbeam entities.
type SubscriptionMoonbeamUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMoonbeamMutation
}

// Where appends a list predicates to the SubscriptionMoonbeamUpdate builder.
func (smu *SubscriptionMoonbeamUpdate) Where(ps ...predicate.SubscriptionMoonbeam) *SubscriptionMoonbeamUpdate {
	smu.mutation.Where(ps...)
	return smu
}

// Mutation returns the SubscriptionMoonbeamMutation object of the builder.
func (smu *SubscriptionMoonbeamUpdate) Mutation() *SubscriptionMoonbeamMutation {
	return smu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (smu *SubscriptionMoonbeamUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, smu.sqlSave, smu.mutation, smu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (smu *SubscriptionMoonbeamUpdate) SaveX(ctx context.Context) int {
	affected, err := smu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (smu *SubscriptionMoonbeamUpdate) Exec(ctx context.Context) error {
	_, err := smu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smu *SubscriptionMoonbeamUpdate) ExecX(ctx context.Context) {
	if err := smu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (smu *SubscriptionMoonbeamUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionmoonbeam.Table, subscriptionmoonbeam.Columns, sqlgraph.NewFieldSpec(subscriptionmoonbeam.FieldID, field.TypeInt))
	if ps := smu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, smu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionmoonbeam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	smu.mutation.done = true
	return n, nil
}

// SubscriptionMoonbeamUpdateOne is the builder for updating a single SubscriptionMoonbeam entity.
type SubscriptionMoonbeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMoonbeamMutation
}

// Mutation returns the SubscriptionMoonbeamMutation object of the builder.
func (smuo *SubscriptionMoonbeamUpdateOne) Mutation() *SubscriptionMoonbeamMutation {
	return smuo.mutation
}

// Where appends a list predicates to the SubscriptionMoonbeamUpdate builder.
func (smuo *SubscriptionMoonbeamUpdateOne) Where(ps ...predicate.SubscriptionMoonbeam) *SubscriptionMoonbeamUpdateOne {
	smuo.mutation.Where(ps...)
	return smuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (smuo *SubscriptionMoonbeamUpdateOne) Select(field string, fields ...string) *SubscriptionMoonbeamUpdateOne {
	smuo.fields = append([]string{field}, fields...)
	return smuo
}

// Save executes the query and returns the updated SubscriptionMoonbeam entity.
func (smuo *SubscriptionMoonbeamUpdateOne) Save(ctx context.Context) (*SubscriptionMoonbeam, error) {
	return withHooks(ctx, smuo.sqlSave, smuo.mutation, smuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (smuo *SubscriptionMoonbeamUpdateOne) SaveX(ctx context.Context) *SubscriptionMoonbeam {
	node, err := smuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (smuo *SubscriptionMoonbeamUpdateOne) Exec(ctx context.Context) error {
	_, err := smuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (smuo *SubscriptionMoonbeamUpdateOne) ExecX(ctx context.Context) {
	if err := smuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (smuo *SubscriptionMoonbeamUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionMoonbeam, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionmoonbeam.Table, subscriptionmoonbeam.Columns, sqlgraph.NewFieldSpec(subscriptionmoonbeam.FieldID, field.TypeInt))
	id, ok := smuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionMoonbeam.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := smuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionmoonbeam.FieldID)
		for _, f := range fields {
			if !subscriptionmoonbeam.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionmoonbeam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := smuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &SubscriptionMoonbeam{config: smuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, smuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionmoonbeam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	smuo.mutation.done = true
	return _node, nil
}
