// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arjunmal1311/only_fans_on_chain/backend/ent/predicate"
	"arjunmal1311/only_fans_on_chain/backend/ent/subscriptionzkevm"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscriptionZkEVMQuery is the builder for querying SubscriptionZkEVM entities.
type SubscriptionZkEVMQuery struct {
	config
	ctx        *QueryContext
	order      []subscriptionzkevm.OrderOption
	inters     []Interceptor
	predicates []predicate.SubscriptionZkEVM
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionZkEVMQuery builder.
func (szeq *SubscriptionZkEVMQuery) Where(ps ...predicate.SubscriptionZkEVM) *SubscriptionZkEVMQuery {
	szeq.predicates = append(szeq.predicates, ps...)
	return szeq
}

// Limit the number of records to be returned by this query.
func (szeq *SubscriptionZkEVMQuery) Limit(limit int) *SubscriptionZkEVMQuery {
	szeq.ctx.Limit = &limit
	return szeq
}

// Offset to start from.
func (szeq *SubscriptionZkEVMQuery) Offset(offset int) *SubscriptionZkEVMQuery {
	szeq.ctx.Offset = &offset
	return szeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (szeq *SubscriptionZkEVMQuery) Unique(unique bool) *SubscriptionZkEVMQuery {
	szeq.ctx.Unique = &unique
	return szeq
}

// Order specifies how the records should be ordered.
func (szeq *SubscriptionZkEVMQuery) Order(o ...subscriptionzkevm.OrderOption) *SubscriptionZkEVMQuery {
	szeq.order = append(szeq.order, o...)
	return szeq
}

// First returns the first SubscriptionZkEVM entity from the query.
// Returns a *NotFoundError when no SubscriptionZkEVM was found.
func (szeq *SubscriptionZkEVMQuery) First(ctx context.Context) (*SubscriptionZkEVM, error) {
	nodes, err := szeq.Limit(1).All(setContextOp(ctx, szeq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionzkevm.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) FirstX(ctx context.Context) *SubscriptionZkEVM {
	node, err := szeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionZkEVM ID from the query.
// Returns a *NotFoundError when no SubscriptionZkEVM ID was found.
func (szeq *SubscriptionZkEVMQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = szeq.Limit(1).IDs(setContextOp(ctx, szeq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionzkevm.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) FirstIDX(ctx context.Context) int {
	id, err := szeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionZkEVM entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionZkEVM entity is found.
// Returns a *NotFoundError when no SubscriptionZkEVM entities are found.
func (szeq *SubscriptionZkEVMQuery) Only(ctx context.Context) (*SubscriptionZkEVM, error) {
	nodes, err := szeq.Limit(2).All(setContextOp(ctx, szeq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionzkevm.Label}
	default:
		return nil, &NotSingularError{subscriptionzkevm.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) OnlyX(ctx context.Context) *SubscriptionZkEVM {
	node, err := szeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionZkEVM ID in the query.
// Returns a *NotSingularError when more than one SubscriptionZkEVM ID is found.
// Returns a *NotFoundError when no entities are found.
func (szeq *SubscriptionZkEVMQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = szeq.Limit(2).IDs(setContextOp(ctx, szeq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionzkevm.Label}
	default:
		err = &NotSingularError{subscriptionzkevm.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) OnlyIDX(ctx context.Context) int {
	id, err := szeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionZkEVMs.
func (szeq *SubscriptionZkEVMQuery) All(ctx context.Context) ([]*SubscriptionZkEVM, error) {
	ctx = setContextOp(ctx, szeq.ctx, ent.OpQueryAll)
	if err := szeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionZkEVM, *SubscriptionZkEVMQuery]()
	return withInterceptors[[]*SubscriptionZkEVM](ctx, szeq, qr, szeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) AllX(ctx context.Context) []*SubscriptionZkEVM {
	nodes, err := szeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionZkEVM IDs.
func (szeq *SubscriptionZkEVMQuery) IDs(ctx context.Context) (ids []int, err error) {
	if szeq.ctx.Unique == nil && szeq.path != nil {
		szeq.Unique(true)
	}
	ctx = setContextOp(ctx, szeq.ctx, ent.OpQueryIDs)
	if err = szeq.Select(subscriptionzkevm.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) IDsX(ctx context.Context) []int {
	ids, err := szeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (szeq *SubscriptionZkEVMQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, szeq.ctx, ent.OpQueryCount)
	if err := szeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, szeq, querierCount[*SubscriptionZkEVMQuery](), szeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) CountX(ctx context.Context) int {
	count, err := szeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (szeq *SubscriptionZkEVMQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, szeq.ctx, ent.OpQueryExist)
	switch _, err := szeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (szeq *SubscriptionZkEVMQuery) ExistX(ctx context.Context) bool {
	exist, err := szeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionZkEVMQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (szeq *SubscriptionZkEVMQuery) Clone() *SubscriptionZkEVMQuery {
	if szeq == nil {
		return nil
	}
	return &SubscriptionZkEVMQuery{
		config:     szeq.config,
		ctx:        szeq.ctx.Clone(),
		order:      append([]subscriptionzkevm.OrderOption{}, szeq.order...),
		inters:     append([]Interceptor{}, szeq.inters...),
		predicates: append([]predicate.SubscriptionZkEVM{}, szeq.predicates...),
		// clone intermediate query.
		sql:  szeq.sql.Clone(),
		path: szeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (szeq *SubscriptionZkEVMQuery) GroupBy(field string, fields ...string) *SubscriptionZkEVMGroupBy {
	szeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionZkEVMGroupBy{build: szeq}
	grbuild.flds = &szeq.ctx.Fields
	grbuild.label = subscriptionzkevm.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (szeq *SubscriptionZkEVMQuery) Select(fields ...string) *SubscriptionZkEVMSelect {
	szeq.ctx.Fields = append(szeq.ctx.Fields, fields...)
	sbuild := &SubscriptionZkEVMSelect{SubscriptionZkEVMQuery: szeq}
	sbuild.label = subscriptionzkevm.Label
	sbuild.flds, sbuild.scan = &szeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionZkEVMSelect configured with the given aggregations.
func (szeq *SubscriptionZkEVMQuery) Aggregate(fns ...AggregateFunc) *SubscriptionZkEVMSelect {
	return szeq.Select().Aggregate(fns...)
}

func (szeq *SubscriptionZkEVMQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range szeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, szeq); err != nil {
				return err
			}
		}
	}
	for _, f := range szeq.ctx.Fields {
		if !subscriptionzkevm.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if szeq.path != nil {
		prev, err := szeq.path(ctx)
		if err != nil {
			return err
		}
		szeq.sql = prev
	}
	return nil
}

func (szeq *SubscriptionZkEVMQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionZkEVM, error) {
	var (
		nodes = []*SubscriptionZkEVM{}
		_spec = szeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionZkEVM).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionZkEVM{config: szeq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, szeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (szeq *SubscriptionZkEVMQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := szeq.querySpec()
	_spec.Node.Columns = szeq.ctx.Fields
	if len(szeq.ctx.Fields) > 0 {
		_spec.Unique = szeq.ctx.Unique != nil && *szeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, szeq.driver, _spec)
}

func (szeq *SubscriptionZkEVMQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionzkevm.Table, subscriptionzkevm.Columns, sqlgraph.NewFieldSpec(subscriptionzkevm.FieldID, field.TypeInt))
	_spec.From = szeq.sql
	if unique := szeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if szeq.path != nil {
		_spec.Unique = true
	}
	if fields := szeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionzkevm.FieldID)
		for i := range fields {
			if fields[i] != subscriptionzkevm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := szeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := szeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := szeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := szeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (szeq *SubscriptionZkEVMQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(szeq.driver.Dialect())
	t1 := builder.Table(subscriptionzkevm.Table)
	columns := szeq.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionzkevm.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if szeq.sql != nil {
		selector = szeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if szeq.ctx.Unique != nil && *szeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range szeq.predicates {
		p(selector)
	}
	for _, p := range szeq.order {
		p(selector)
	}
	if offset := szeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := szeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubscriptionZkEVMGroupBy is the group-by builder for SubscriptionZkEVM entities.
type SubscriptionZkEVMGroupBy struct {
	selector
	build *SubscriptionZkEVMQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (szegb *SubscriptionZkEVMGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionZkEVMGroupBy {
	szegb.fns = append(szegb.fns, fns...)
	return szegb
}

// Scan applies the selector query and scans the result into the given value.
func (szegb *SubscriptionZkEVMGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, szegb.build.ctx, ent.OpQueryGroupBy)
	if err := szegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionZkEVMQuery, *SubscriptionZkEVMGroupBy](ctx, szegb.build, szegb, szegb.build.inters, v)
}

func (szegb *SubscriptionZkEVMGroupBy) sqlScan(ctx context.Context, root *SubscriptionZkEVMQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(szegb.fns))
	for _, fn := range szegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*szegb.flds)+len(szegb.fns))
		for _, f := range *szegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*szegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := szegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionZkEVMSelect is the builder for selecting fields of SubscriptionZkEVM entities.
type SubscriptionZkEVMSelect struct {
	*SubscriptionZkEVMQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (szes *SubscriptionZkEVMSelect) Aggregate(fns ...AggregateFunc) *SubscriptionZkEVMSelect {
	szes.fns = append(szes.fns, fns...)
	return szes
}

// Scan applies the selector query and scans the result into the given value.
func (szes *SubscriptionZkEVMSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, szes.ctx, ent.OpQuerySelect)
	if err := szes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionZkEVMQuery, *SubscriptionZkEVMSelect](ctx, szes.SubscriptionZkEVMQuery, szes, szes.inters, v)
}

func (szes *SubscriptionZkEVMSelect) sqlScan(ctx context.Context, root *SubscriptionZkEVMQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(szes.fns))
	for _, fn := range szes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*szes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := szes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
