// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arjunmal1311/fans_flow_on_chain/backend/ent/predicate"
	"arjunmal1311/fans_flow_on_chain/backend/ent/subscriptionmetis"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscriptionMetisDelete is the builder for deleting a SubscriptionMetis entity.
type SubscriptionMetisDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionMetisMutation
}

// Where appends a list predicates to the SubscriptionMetisDelete builder.
func (smd *SubscriptionMetisDelete) Where(ps ...predicate.SubscriptionMetis) *SubscriptionMetisDelete {
	smd.mutation.Where(ps...)
	return smd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (smd *SubscriptionMetisDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, smd.sqlExec, smd.mutation, smd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (smd *SubscriptionMetisDelete) ExecX(ctx context.Context) int {
	n, err := smd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (smd *SubscriptionMetisDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionmetis.Table, sqlgraph.NewFieldSpec(subscriptionmetis.FieldID, field.TypeInt))
	if ps := smd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, smd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	smd.mutation.done = true
	return affected, err
}

// SubscriptionMetisDeleteOne is the builder for deleting a single SubscriptionMetis entity.
type SubscriptionMetisDeleteOne struct {
	smd *SubscriptionMetisDelete
}

// Where appends a list predicates to the SubscriptionMetisDelete builder.
func (smdo *SubscriptionMetisDeleteOne) Where(ps ...predicate.SubscriptionMetis) *SubscriptionMetisDeleteOne {
	smdo.smd.mutation.Where(ps...)
	return smdo
}

// Exec executes the deletion query.
func (smdo *SubscriptionMetisDeleteOne) Exec(ctx context.Context) error {
	n, err := smdo.smd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionmetis.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (smdo *SubscriptionMetisDeleteOne) ExecX(ctx context.Context) {
	if err := smdo.Exec(ctx); err != nil {
		panic(err)
	}
}
