// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arjunmal1311/fans_flow_on_chain/backend/ent/predicate"
	"arjunmal1311/fans_flow_on_chain/backend/ent/subscriptionmetis"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscriptionMetisQuery is the builder for querying SubscriptionMetis entities.
type SubscriptionMetisQuery struct {
	config
	ctx        *QueryContext
	order      []subscriptionmetis.OrderOption
	inters     []Interceptor
	predicates []predicate.SubscriptionMetis
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionMetisQuery builder.
func (smq *SubscriptionMetisQuery) Where(ps ...predicate.SubscriptionMetis) *SubscriptionMetisQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit the number of records to be returned by this query.
func (smq *SubscriptionMetisQuery) Limit(limit int) *SubscriptionMetisQuery {
	smq.ctx.Limit = &limit
	return smq
}

// Offset to start from.
func (smq *SubscriptionMetisQuery) Offset(offset int) *SubscriptionMetisQuery {
	smq.ctx.Offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *SubscriptionMetisQuery) Unique(unique bool) *SubscriptionMetisQuery {
	smq.ctx.Unique = &unique
	return smq
}

// Order specifies how the records should be ordered.
func (smq *SubscriptionMetisQuery) Order(o ...subscriptionmetis.OrderOption) *SubscriptionMetisQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// First returns the first SubscriptionMetis entity from the query.
// Returns a *NotFoundError when no SubscriptionMetis was found.
func (smq *SubscriptionMetisQuery) First(ctx context.Context) (*SubscriptionMetis, error) {
	nodes, err := smq.Limit(1).All(setContextOp(ctx, smq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionmetis.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) FirstX(ctx context.Context) *SubscriptionMetis {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionMetis ID from the query.
// Returns a *NotFoundError when no SubscriptionMetis ID was found.
func (smq *SubscriptionMetisQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(1).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionmetis.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) FirstIDX(ctx context.Context) int {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionMetis entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionMetis entity is found.
// Returns a *NotFoundError when no SubscriptionMetis entities are found.
func (smq *SubscriptionMetisQuery) Only(ctx context.Context) (*SubscriptionMetis, error) {
	nodes, err := smq.Limit(2).All(setContextOp(ctx, smq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionmetis.Label}
	default:
		return nil, &NotSingularError{subscriptionmetis.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) OnlyX(ctx context.Context) *SubscriptionMetis {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionMetis ID in the query.
// Returns a *NotSingularError when more than one SubscriptionMetis ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *SubscriptionMetisQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(2).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionmetis.Label}
	default:
		err = &NotSingularError{subscriptionmetis.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) OnlyIDX(ctx context.Context) int {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionMetisSlice.
func (smq *SubscriptionMetisQuery) All(ctx context.Context) ([]*SubscriptionMetis, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryAll)
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionMetis, *SubscriptionMetisQuery]()
	return withInterceptors[[]*SubscriptionMetis](ctx, smq, qr, smq.inters)
}

// AllX is like All, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) AllX(ctx context.Context) []*SubscriptionMetis {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionMetis IDs.
func (smq *SubscriptionMetisQuery) IDs(ctx context.Context) (ids []int, err error) {
	if smq.ctx.Unique == nil && smq.path != nil {
		smq.Unique(true)
	}
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryIDs)
	if err = smq.Select(subscriptionmetis.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) IDsX(ctx context.Context) []int {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *SubscriptionMetisQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryCount)
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, smq, querierCount[*SubscriptionMetisQuery](), smq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *SubscriptionMetisQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryExist)
	switch _, err := smq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *SubscriptionMetisQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionMetisQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *SubscriptionMetisQuery) Clone() *SubscriptionMetisQuery {
	if smq == nil {
		return nil
	}
	return &SubscriptionMetisQuery{
		config:     smq.config,
		ctx:        smq.ctx.Clone(),
		order:      append([]subscriptionmetis.OrderOption{}, smq.order...),
		inters:     append([]Interceptor{}, smq.inters...),
		predicates: append([]predicate.SubscriptionMetis{}, smq.predicates...),
		// clone intermediate query.
		sql:  smq.sql.Clone(),
		path: smq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (smq *SubscriptionMetisQuery) GroupBy(field string, fields ...string) *SubscriptionMetisGroupBy {
	smq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionMetisGroupBy{build: smq}
	grbuild.flds = &smq.ctx.Fields
	grbuild.label = subscriptionmetis.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (smq *SubscriptionMetisQuery) Select(fields ...string) *SubscriptionMetisSelect {
	smq.ctx.Fields = append(smq.ctx.Fields, fields...)
	sbuild := &SubscriptionMetisSelect{SubscriptionMetisQuery: smq}
	sbuild.label = subscriptionmetis.Label
	sbuild.flds, sbuild.scan = &smq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionMetisSelect configured with the given aggregations.
func (smq *SubscriptionMetisQuery) Aggregate(fns ...AggregateFunc) *SubscriptionMetisSelect {
	return smq.Select().Aggregate(fns...)
}

func (smq *SubscriptionMetisQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range smq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, smq); err != nil {
				return err
			}
		}
	}
	for _, f := range smq.ctx.Fields {
		if !subscriptionmetis.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *SubscriptionMetisQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionMetis, error) {
	var (
		nodes = []*SubscriptionMetis{}
		_spec = smq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionMetis).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionMetis{config: smq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (smq *SubscriptionMetisQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	_spec.Node.Columns = smq.ctx.Fields
	if len(smq.ctx.Fields) > 0 {
		_spec.Unique = smq.ctx.Unique != nil && *smq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *SubscriptionMetisQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionmetis.Table, subscriptionmetis.Columns, sqlgraph.NewFieldSpec(subscriptionmetis.FieldID, field.TypeInt))
	_spec.From = smq.sql
	if unique := smq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if smq.path != nil {
		_spec.Unique = true
	}
	if fields := smq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionmetis.FieldID)
		for i := range fields {
			if fields[i] != subscriptionmetis.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *SubscriptionMetisQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(subscriptionmetis.Table)
	columns := smq.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionmetis.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.ctx.Unique != nil && *smq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SubscriptionMetisGroupBy is the group-by builder for SubscriptionMetis entities.
type SubscriptionMetisGroupBy struct {
	selector
	build *SubscriptionMetisQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *SubscriptionMetisGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionMetisGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the selector query and scans the result into the given value.
func (smgb *SubscriptionMetisGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, smgb.build.ctx, ent.OpQueryGroupBy)
	if err := smgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionMetisQuery, *SubscriptionMetisGroupBy](ctx, smgb.build, smgb, smgb.build.inters, v)
}

func (smgb *SubscriptionMetisGroupBy) sqlScan(ctx context.Context, root *SubscriptionMetisQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*smgb.flds)+len(smgb.fns))
		for _, f := range *smgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*smgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionMetisSelect is the builder for selecting fields of SubscriptionMetis entities.
type SubscriptionMetisSelect struct {
	*SubscriptionMetisQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sms *SubscriptionMetisSelect) Aggregate(fns ...AggregateFunc) *SubscriptionMetisSelect {
	sms.fns = append(sms.fns, fns...)
	return sms
}

// Scan applies the selector query and scans the result into the given value.
func (sms *SubscriptionMetisSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sms.ctx, ent.OpQuerySelect)
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionMetisQuery, *SubscriptionMetisSelect](ctx, sms.SubscriptionMetisQuery, sms, sms.inters, v)
}

func (sms *SubscriptionMetisSelect) sqlScan(ctx context.Context, root *SubscriptionMetisQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sms.fns))
	for _, fn := range sms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
