// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arjunmal1311/only_fans_on_chain/backend/ent/subscriptionzkevm"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SubscriptionZkEVM is the model entity for the SubscriptionZkEVM schema.
type SubscriptionZkEVM struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionZkEVM) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionzkevm.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionZkEVM fields.
func (sze *SubscriptionZkEVM) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionzkevm.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sze.ID = int(value.Int64)
		default:
			sze.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionZkEVM.
// This includes values selected through modifiers, order, etc.
func (sze *SubscriptionZkEVM) Value(name string) (ent.Value, error) {
	return sze.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionZkEVM.
// Note that you need to call SubscriptionZkEVM.Unwrap() before calling this method if this SubscriptionZkEVM
// was returned from a transaction, and the transaction was committed or rolled back.
func (sze *SubscriptionZkEVM) Update() *SubscriptionZkEVMUpdateOne {
	return NewSubscriptionZkEVMClient(sze.config).UpdateOne(sze)
}

// Unwrap unwraps the SubscriptionZkEVM entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sze *SubscriptionZkEVM) Unwrap() *SubscriptionZkEVM {
	_tx, ok := sze.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionZkEVM is not a transactional entity")
	}
	sze.config.driver = _tx.drv
	return sze
}

// String implements the fmt.Stringer.
func (sze *SubscriptionZkEVM) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionZkEVM(")
	builder.WriteString(fmt.Sprintf("id=%v", sze.ID))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionZkEVMs is a parsable slice of SubscriptionZkEVM.
type SubscriptionZkEVMs []*SubscriptionZkEVM
