// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ModelsColumns holds the columns for the "models" table.
	ModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ModelsTable holds the schema information for the "models" table.
	ModelsTable = &schema.Table{
		Name:       "models",
		Columns:    ModelsColumns,
		PrimaryKey: []*schema.Column{ModelsColumns[0]},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
	}
	// SubscriptionMetisColumns holds the columns for the "subscription_metis" table.
	SubscriptionMetisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SubscriptionMetisTable holds the schema information for the "subscription_metis" table.
	SubscriptionMetisTable = &schema.Table{
		Name:       "subscription_metis",
		Columns:    SubscriptionMetisColumns,
		PrimaryKey: []*schema.Column{SubscriptionMetisColumns[0]},
	}
	// SubscriptionMoonbeamsColumns holds the columns for the "subscription_moonbeams" table.
	SubscriptionMoonbeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SubscriptionMoonbeamsTable holds the schema information for the "subscription_moonbeams" table.
	SubscriptionMoonbeamsTable = &schema.Table{
		Name:       "subscription_moonbeams",
		Columns:    SubscriptionMoonbeamsColumns,
		PrimaryKey: []*schema.Column{SubscriptionMoonbeamsColumns[0]},
	}
	// SubscriptionZkEvMsColumns holds the columns for the "subscription_zk_ev_ms" table.
	SubscriptionZkEvMsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// SubscriptionZkEvMsTable holds the schema information for the "subscription_zk_ev_ms" table.
	SubscriptionZkEvMsTable = &schema.Table{
		Name:       "subscription_zk_ev_ms",
		Columns:    SubscriptionZkEvMsColumns,
		PrimaryKey: []*schema.Column{SubscriptionZkEvMsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ModelsTable,
		SubscriptionsTable,
		SubscriptionMetisTable,
		SubscriptionMoonbeamsTable,
		SubscriptionZkEvMsTable,
		UsersTable,
	}
)

func init() {
}
